#!/bin/bash
rm -rf build
mkdir -p build
cp bunniesx.pyx build
cp -r images build
cd build
schafer -P android
schafer -P android -m bunniesx.pyx -p com.mdqinc.bunnymarkx -a images
cp com.mdqinc.bunnymarkx ..
cd build/android/android_project
ant debug install
cd ../../../..

